### ISSUE TITLE
1107 on obtaining certificate for just this image

### ISSUE THREAD

**Issue by Saik0Shinigami** [caprover/nginx-reverse-proxy#2]
I want to implement caprover, it seems right up my alley but I'm stuck in a catch 22 at the moment on the particular issue of where caprover has to be placed. This docker appears to be the resolution to the problem of caprover needing the wildcard spot where someone might have other services that needs to reside on the same domain.

I can get through everything, working through NAT, ports, DNS. This image appears to be at face value capable of replacing my clunky (and probably kludgy) Apache reverse proxy. From and HTTP perspective it works fine. But for the life of me I'm unable to activate the HTTPS button for this image. Other images all work fine, the primary domain is properly joined. I'm able to get a couple wordpresses up, dokuwiki, teamspeak... virtually any other "packaged" app (haven't gone forward with my own images yet as this issue stops me from keeping the platform up and running) up with http and https access... But this container doesn't appear to let me activate.

Specifically I am able to proxy normal http requests to other services/servers in my network, but cannot activate https within caprover for only this image. Images ran will reach target via http, but throw to the "nothing is here" caprover page when https is attempted. Is there a resolution to this that I'm apparently too stupid to see? I can't run caprover at all in the position that it works best when a lot of backend services require https to function.

**Comment by githubsaturn** [comment]
Not sure if In understand what the issue is here. Are you saying under the same setup, enabling HTTPs doesn't work for this particular image?

**Comment by Saik0Shinigami** [comment]
Correct. So brand new install of Caprover. And sorry if it was wordy or impossible to understand... I wrote it sleep deprived.

Create many local one click apps... all activate fine clicking HTTPS (grabs certs and everything) and functions fine.

This particular image (and only this one that I've ran into so far). I'm unable to activate HTTPS in the Caprover UI.

The image itself appears to work mostly? I can access things via http when configured. But many of my sites require https and automatically redirect to https which then breaks because I can't pull a cert for this image.

**Comment by githubsaturn** [comment]
There is nothing specific about this image. One possibility is that you've reached your limit for free SSL certificate creation. I think it's about 20 new certificates per week. Try this:
- Create a new app
- Enable HTTPS for that app
- Enable Force HTTPS (if needed)
- Go to the deploy tab, and manually deploy the image:
- Under ` Method 6: Deploy via ImageName`, enter: `caprover/nginx-reverse-proxy:latest`
- Deploy and wait until it is deployed.
- Then navigate to the second tab, `App Configs` and enter the following two environment variables:
```
UPSTREAM_HTTP_ADDRESS=https://youraddress.com
CLIENT_MAX_BODY_SIZE=256M
```

Does this work?

**Comment by Saik0Shinigami** [comment]
Sorry forgot this issue was open. I don't remember how I resolved it, but I did. I do remember it not being directly an image issue. Probably something silly like dns.
