### ISSUE TITLE
Detect/warn/remove final slash from UPSTREAM_HTTP_ADDRESS.

### ISSUE THREAD

**Issue by digitalsanity** [caprover/nginx-reverse-proxy#3]
I lost a couple of hours today tracking down the strangest issues while using the proxy, and they were all because I was including a final slash in UPSTREAM_HTTP_ADDRESS when I should not have.

**Comment by githubsaturn** [comment]
I am assuming you used the one-click app. I just added some notes to warn users about this:
https://github.com/caprover/one-click-apps/commit/71d95e60ed5b3dd391b6f346218a6d892463fe1a
