### ISSUE TITLE
Receiving 404

### ISSUE THREAD

**Issue by dgoldm** [caprover/nginx-reverse-proxy#7]
Is this a standalone application? Or does it require CapRover?
I don't have CapRover installed. I just executed the docker run command as per the readme, then pointed a browser to http://localhost:1234. 
I received the following page:
![image](https://github.com/caprover/nginx-reverse-proxy/assets/11911957/2a2dd814-a98c-4cd7-a00e-7b2f64d1eea8)
Tried on a Windows 11 machine and on an Ubuntu 22.04 Hyper-V VM.

Also tried setting UPSTREAM_HTTP_ADDRESS='https://google.com', received a Google 404

**Comment by githubsaturn** [comment]
It's because the HOST header is not being replaced. The readme example is just an example, not ac actual use case. The reverse proxy is used when the upstream is something like `123.123.123.123:9000`
